
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ParkingSystem.Appdata
{

using System;
    using System.Collections.Generic;
    
public partial class Reservation
{

    public int id { get; set; }

    public Nullable<int> plateNo { get; set; }

    public string VehicleType { get; set; }

    public string OwnerName { get; set; }

    public Nullable<int> Payment { get; set; }

    public Nullable<System.DateTime> date { get; set; }

}

}
