
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ParkingSystem.Appdata
{

using System;
    using System.Collections.Generic;
    
public partial class slotItems
{

    public int id { get; set; }

    public string floor1 { get; set; }

    public string floor2 { get; set; }

    public string floor3 { get; set; }

}

}
