
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ParkingSystem.Appdata
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public int UserID { get; set; }

    public string Name { get; set; }

    public string userGender { get; set; }

    public string userPhone { get; set; }

    public string userEmail { get; set; }

    public string userAddress { get; set; }

    public string userName { get; set; }

    public string userPass { get; set; }

    public Nullable<int> roleId { get; set; }

}

}
