
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ParkingSystem.Appdata
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Slots
{

    public int slotId { get; set; }

    public string slotNumber { get; set; }

    public string floorNumber { get; set; }

}

}
